apiVersion: v1
data:
  dbserver: c3Fsc2VydmVyZXV0ODI1MC5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  password: Q2hhbmdlTWUxIQ==
  username: c3FsYWRtaW5lVXQ4MjUw
kind: Secret
metadata:
  name: db-user-pass
  namespace: default
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: default
spec:
  selector:
    matchLabels:
      service: poi
  replicas: 1
  template:
    metadata:
      labels:
        service: poi
    spec:
      containers:
      - name: poi
        image: registryeut8250.azurecr.io/poi:1.0
        imagePullPolicy: Always
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db-user-pass
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: db-user-pass
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                key: dbserver
                name: db-user-pass        

---

apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    service: poi
  sessionAffinity: None
  type: ClusterIP