apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-web
  namespace: web
subjects:
- kind: User
  name: webdev@msftopenhack6733ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-web
  namespace: web
subjects:
- kind: User
  name: apidev@msftopenhack6733ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-api
  namespace: api
subjects:
- kind: User
  name: apidev@msftopenhack6733ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-api
  namespace: api
subjects:
- kind: User
  name: webdev@msftopenhack6733ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
