apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 5ca2587d-9263-44fc-b34f-c6cbeeb5cc56
  labels:
    azure.workload.identity/use: "true"
  name: trip-insight-vault-user
  namespace: api

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-user-pass
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "5ca2587d-9263-44fc-b34f-c6cbeeb5cc56"
    keyvaultName: "Tripinsightsvalut"  
    objects:  |
      array:
        - |
          objectName: username
          objectType: secret
          objectAlias: SQL_USER                        
        - |
          objectName: password
          objectType: secret
          objectAlias: SQL_PASSWORD
        - |
          objectName: dbserver
          objectType: secret
          objectAlias: SQL_SERVER
    tenantId: "5dc41684-847a-41d7-84e0-401325d9d605"
