apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 3
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryeut8250.azurecr.io/tripviewer:1.0
        imagePullPolicy: Always
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile-service:8080"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips-service:8080"
---

apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
  sessionAffinity: None
  type: LoadBalancer