apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 3
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryeut8250.azurecr.io/tripviewer:1.0
        imagePullPolicy: Always
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile-service.api:8080"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips-service.api:8080"
---

apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripviewer-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "20.165.176.143"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tripviewer
            port: 
              number: 8080   