apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: default
spec:
  selector:
    matchLabels:
      service: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        service: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryeut8250.azurecr.io/userprofile:1.0
        imagePullPolicy: Always
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db-user-pass
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: db-user-pass
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                key: dbserver
                name: db-user-pass        

---

apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    service: userprofile
  sessionAffinity: None
  type: ClusterIP